version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'all'
    rebase-strategy: 'disabled'
    groups:
      dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: 'chore'
      include: 'scope'
