version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    rebase-strategy: "disabled"
    groups:
      dependencies:
        patterns:
          - "*"
    target-branch: "v3"
    commit-message:
      prefix: "chore"
      include: "scope"
