# https://taskfile.dev
version: '3'
env:
  WORKSPACE_DIR: '{{.ROOT_DIR}}'
  XDG_CACHE_HOME: '{{.XDG_CACHE_HOME | default (joinPath .HOME ".cache")}}'
includes:
  shell: src/shell
  node: src/node
  git: src/git

tasks:
  default:
    # attributes
    desc: タスクの一覧を表示する.
    silent: true
    cmds:
      - task --list
