# Memory size
# 🟢 Builtin default: min("4GiB", half of host memory)
memory: 2GiB

# Disk size
# 🟢 Builtin default: "100GiB"
disk: 40GiB

networks:
- lima: shared
  # MAC address of the instance; lima will pick one based on the instance name,
  # so DHCP assigned ip addresses should remain constant over instance restarts.
  macAddress: ""
  # Interface name, defaults to "lima0", "lima1", etc.
  interface: ""