[[hints.enabled]]
command = "open"
hyperlinks = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
post_processing = true
mouse = { mods = "Command | Control", enabled = true }