#cloud-config
## common configuration
timezone: Asia/Tokyo
ssh_import_id:
  - "gh:zaky-jp"

## apt configuration
apt:
  primary:
    - arches:
          - default
      search:
        - "https://ftp.udx.icscoe.jp/Linux/ubuntu/" # prob fastest mirror ever
        - "http://jp.archive.ubuntu.com/ubuntu/"
        - "http://archive.ubuntu.com/ubuntu/"
      search_dns: false
  security:
    - arches:
        - default
      uri: "http://security.ubuntu.com/ubuntu/" # only trust genuine security mirrors
      search_dns: false
  conf: |
    APT {
      Get {
        Assume-Yes "true";
        Install-Recommends "false";
      };
    };
package_update: true
package_upgrade: true
package_reboot_if_required: true
snap:
  commands:
    - ['refresh']
packages:
  - systemd-container
