#!/usr/bin/env zsh

if (( $+commands[alacritty] )); then
  function gssh() {
    echo "Starting ssh in a new alacritty window:"
    nohup alacritty --command ssh "${@}" -- 1>/dev/null 2>&1 &
    # TERM variable is always send to the remote server
    # this means alacritty.terminfo needs to be present at remote server
    # otherwise emulate xterm-256color:
    # nohup alacritty --option env.TERM=xterm-256color --command ssh "${@}" -- 1>/dev/null 2>&1 &
  }
fi

# vim: filetype=zsh :
