# https://taskfile.dev
version: '3'

tasks:
  default:
    # attributes
    desc: node.jsをインストールする.
    summary: |-
      node.jsの最新版をインストールする.
      インストールにはvoltaを利用する.
    aliases:
      - install-node
    # conditions
    run: once
    deps:
      - install-volta
    status:
      - test $(volta list --format plain node | wc -l) -eq 1
    # runner
    cmds:
      - volta install node@latest

  volta:
    # attributes
    desc: voltaをインストールする.
    summary: |-
      voltaからインストールスクリプトをダウンロードし、実行する.
    aliases:
      - install-volta
    # conditions
    run: once
    status:
      - command -v volta
    preconditions:
      - sh: test -n "${VOLTA_HOME}"
        msg: $VOLTA_HOMEが未定義です.
    # runner
    cmds:
      - curl -fsSL https://get.volta.sh | bash -s -- --skip-setup

  npm:
    # attributes
    desc: npmをインストールする.
    summary: |-
      npmの最新版をインストールする.
      インストールにはvoltaを利用する.
    aliases:
      - install-npm
    # conditions
    run: once
    deps:
      - install-node
    status:
      - test $(volta list --format plain npm | wc -l) -eq 1
    # runner
    cmds:
      - volta install npm@latest

  packages:
    # attributes
    desc: npmからpackageをインストールする.
    summary: |-
      npmからpackageをインストールする.
      $WORKSPACE_DIR/package.jsonを参照する.
    aliases:
      - install-packages
    # conditions
    run: once
    preconditions:
      - test -e package.json
    deps:
      - install-npm
    # runner
    cmds:
      - npm install
      - npm update
